-- ============================================================
-- Hakeela HakPortal — seed
-- Courses are created by admins in the app (Courses & Programs → New Course),
-- so there is no sample-course seed. This file is intentionally empty.
--
-- To clear the earlier sample courses that were seeded during setup, run:
--
--   delete from public.courses
--   where slug in ('data-analysis','product-design','web-development',
--                  'intro-computer','excel','changemaker');
--   -- (their modules/lessons/assessments cascade-delete automatically)
-- ============================================================
